RDCC-3923: LRD-data-load Remove Deprecated Jcenter Repository
hmcts/rd-location-ref-data-load pull request #228
Opened 2022-01-21 14:45 UTC by ishratt

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-3923

### Change description ###
Removed deprecated jcenter repository

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-01-31 13:34 UTC, SujeethKumarAri requested changes

2022-01-31 13:34 UTC, SujeethKumarAri commented on build.gradle
> +  implementation 'com.github.hmcts.java-logging:logging:5.1.7'
can you upgrade versions.reformLogging to latest and use that instead of using hard code `5.1.7`

2022-01-31 13:34 UTC, SujeethKumarAri commented on build.gradle
> +  implementation 'com.github.hmcts.java-logging:logging-appinsights:5.1.7'
can you upgrade versions.reformLogging to latest and use that instead of using hard code `5.1.7`

2022-01-31 16:27 UTC, SujeethKumarAri approved these changes

2022-01-31 16:29 UTC, SujeethKumarAri commented
@ishratt - thanks for addressing the review comments. Have you ran the job locally to see that the files are getting processed? just wanted to make sure job is running successfully or not

2022-02-10 09:37 UTC, kavithagade12 approved these changes

2022-02-10 10:02 UTC, SujeethKumarAri approved these changes

2022-02-11 14:39 UTC, merged