Rdcc 3979 added scripts
hmcts/rd-location-ref-data-load pull request #238
Opened 2022-02-18 12:25 UTC by shivajilokare

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-02-21 18:55 UTC, SujeethKumarAri requested changes

2022-02-21 18:55 UTC, SujeethKumarAri commented on src/main/resources/db/migration/V1_16__update_service_ticket_code_for_sscs.sql
> +DELETE FROM judicial_service_code_mapping WHERE service_id ='21' OR service_id ='55';
you can move these scripts to the above created file, so that we can avoid having an extra file

2022-02-21 18:57 UTC, SujeethKumarAri commented
hi @shivajilokare  - you need to make changes in judicial data load instead of location data load :)

2022-02-22 09:51 UTC, shivajilokare commented
will raise correct PR closing this .

2022-02-22 09:51 UTC, closed without merging