DTSRD-2505: Add new column (External_Court_Name) to the court_venue table
hmcts/rd-location-ref-data-load pull request #414
Opened 2024-05-20 21:58 UTC by kiran-yenigala-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-05-21 08:20 UTC, lukasz-wolski approved these changes

2024-05-22 13:18 UTC, rajkatla-hmcts requested changes

2024-05-22 13:18 UTC, rajkatla-hmcts commented on src/functionalTest/resources/db/testmigration/V1_26__alter_tables_add_columns.sql
> +ALTER TABLE COURT_VENUE RENAME COLUMN SHORT_COURT_NAME TO EXTERNAL_SHORT_NAME;
add data to Extertal_Short_Name and verify data loaded for this column for all test data csv files

2024-05-22 13:18 UTC, rajkatla-hmcts commented on src/functionalTest/resources/application-integration.yml
> -      venue_ou_code, mrd_building_location_id, mrd_venue_id, service_url, fact_url, mrd_created_time, mrd_updated_time, mrd_deleted_time, short_court_name, created_time, updated_time)
looks like these tests are not functional , can we change this directory name to integrationTest

2024-05-28 16:05 UTC, rajkatla-hmcts submitted a review, later dismissed

2024-05-28 18:12 UTC, rajkatla-hmcts approved these changes

2024-05-29 07:27 UTC, SabinaHMCTS approved these changes

2024-05-29 07:28 UTC, merged