refactor: Truncate & Insert Support for LRD load(RDCC-1943)
hmcts/rd-location-ref-data-load pull request #49
Opened 2020-10-13 12:10 UTC by abhijitdiwan

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-1943

### Change description ###
refactor: Truncate & Insert Support for LRD load(RDCC-1943)

**Does this PR introduce a breaking change?** (check one with "x")
No

2020-10-13 22:24 UTC, shashank-rastogi requested changes

2020-10-14 10:08 UTC, abhijitdiwan commented on src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
>              ServiceToCcdCaseType.builder().ccdCaseType("service1")
no we ar not validating column names we jut expecting 3 columns.As a framework we put that as hold. Only if column more we will get header validation error (eg. 4 or 5) lesser columns we disabled in framework.

2020-10-14 10:10 UTC, abhijitdiwan commented on src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
> +        ), 4);
It is better to validate right..as it will validate or audits which we except after inserts in func test data.

2020-10-14 14:49 UTC, abhijitdiwan commented on src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
> +
done

2020-10-15 09:44 UTC, shashank-rastogi submitted a review, later dismissed

2020-10-15 09:47 UTC, pksaxena01 submitted a review, later dismissed
Approved

2020-10-15 14:10 UTC, shreedhar-hmcts approved these changes

2020-10-15 14:14 UTC, pksaxena01 approved these changes
Approved

2020-10-15 14:14 UTC, merged